### ISSUE TITLE
'as_matrix()' should be replaced with 'values'

### ISSUE THREAD

**Issue by gaurbans** [nyuvis/partial_dependence#2]
There seems to be an error now when running 'PartialDependence' because Pandas has deprecated `df.as_matrix()` in favor of `df.values`. This should accordingly be updated in lines 504 and 506 in partial_dependence.py.

**Comment by paolotamag** [comment]
Hello, I did the fix as requested. 
Only on GitHub, not on PyPi yet
Let us know if it worked and we might be able to update there too.

Thanks
Paolo
